/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PassivosRouteImport } from './routes/passivos'
import { Route as RoadmapRouteImport } from './routes/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PassivosRoute = PassivosRouteImport.update({
  id: '/passivos',
  path: '/passivos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entradas': typeof EntradasRoute
  '/historico': typeof HistoricoRoute
  '/passivos': typeof PassivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entradas': typeof EntradasRoute
  '/historico': typeof HistoricoRoute
  '/passivos': typeof PassivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entradas': typeof EntradasRoute
  '/historico': typeof HistoricoRoute
  '/passivos': typeof PassivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entradas' | '/historico' | '/passivos' | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entradas' | '/historico' | '/passivos' | '/roadmap'
  id: '__root__' | '/' | '/entradas' | '/historico' | '/passivos' | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntradasRoute: typeof EntradasRoute
  HistoricoRoute: typeof HistoricoRoute
  PassivosRoute: typeof PassivosRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passivos': {
      id: '/passivos'
      path: '/passivos'
      fullPath: '/passivos'
      preLoaderRoute: typeof PassivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntradasRoute: EntradasRoute,
  HistoricoRoute: HistoricoRoute,
  PassivosRoute: PassivosRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
